# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amux < Formula
  desc "Terminal multiplexer for human+agent workflows"
  homepage "https://github.com/weill-labs/amux"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weill-labs/amux/releases/download/v0.1.0/amux_0.1.0_darwin_amd64.tar.gz"
      sha256 "784fa2bff5c3b9d6f350c99e7d7f1190a9f8c127bf0a2d23c97a7b4b877544d7"

      define_method(:install) do
        bin.install "amux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weill-labs/amux/releases/download/v0.1.0/amux_0.1.0_darwin_arm64.tar.gz"
      sha256 "519bef973b12c5f9d4b17af3df7c30a36d34a2d1ada91e34b74baa221fe05a8f"

      define_method(:install) do
        bin.install "amux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/weill-labs/amux/releases/download/v0.1.0/amux_0.1.0_linux_amd64.tar.gz"
      sha256 "43a6bbe5c84bc4ab49a1b2f2912398e6126b1db70c0233851e369ec7ada487a2"
      define_method(:install) do
        bin.install "amux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weill-labs/amux/releases/download/v0.1.0/amux_0.1.0_linux_arm64.tar.gz"
      sha256 "2919e3c6fcbe7fb5a67990db3ab4bd6aa2a88e51ec6318aca65a546d6d24f902"
      define_method(:install) do
        bin.install "amux"
      end
    end
  end

  def caveats
    <<~EOS
      On first server start, amux installs its terminfo entry into ~/.terminfo.
      You can also run:
        amux install-terminfo
    EOS
  end

  test do
    system "#{bin}/amux", "version"
  end
end
