# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Amux < Formula
  desc "Terminal multiplexer for human+agent workflows"
  homepage "https://github.com/weill-labs/amux"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/weill-labs/amux/releases/download/v0.4.0/amux_0.4.0_darwin_amd64.tar.gz"
      sha256 "9a49d07e8d909bf9dd79a1cffc2656c725f3f8e2bbe37896ed00894cd9ac2acb"

      define_method(:install) do
        bin.install "amux"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/weill-labs/amux/releases/download/v0.4.0/amux_0.4.0_darwin_arm64.tar.gz"
      sha256 "179181077a7773c88ebc742fc748cfe794b888244a6187777e8959a74af67c10"

      define_method(:install) do
        bin.install "amux"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/weill-labs/amux/releases/download/v0.4.0/amux_0.4.0_linux_amd64.tar.gz"
      sha256 "6ccb7acf3e6fca338938e22e7d86bec9eaf566d544c4597e05c16a4879166864"
      define_method(:install) do
        bin.install "amux"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/weill-labs/amux/releases/download/v0.4.0/amux_0.4.0_linux_arm64.tar.gz"
      sha256 "9fc864ad7aa07f524dc3f93163ac8cbf63d3e14d805dcd5fabf84849f53d4de8"
      define_method(:install) do
        bin.install "amux"
      end
    end
  end

  def caveats
    <<~EOS
      On first server start, amux installs its terminfo entry into ~/.terminfo.
      You can also run:
        amux install-terminfo
    EOS
  end

  test do
    system "#{bin}/amux", "version"
  end
end
